// <auto-generated />
using System;
using ComexApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComexApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComexApi.Models.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ETA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ETB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ETD")
                        .HasColumnType("datetime2");

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Porto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TabelaDeEscalas");
                });

            modelBuilder.Entity("ComexApi.Models.Manifesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PortoDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortoOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("TabelaDeManifestos");
                });

            modelBuilder.Entity("ComexApi.Models.Vinculo", b =>
                {
                    b.Property<int>("ManifestoId")
                        .HasColumnType("int");

                    b.Property<int>("EscalaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataVinculacao")
                        .HasColumnType("datetime2");

                    b.HasKey("ManifestoId", "EscalaId");

                    b.HasIndex("EscalaId");

                    b.ToTable("TabelaDeVinculos");
                });

            modelBuilder.Entity("ComexApi.Models.Vinculo", b =>
                {
                    b.HasOne("ComexApi.Models.Escala", "Escala")
                        .WithMany("ManifestosVinculados")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComexApi.Models.Manifesto", "Manifesto")
                        .WithMany("EscalasVinculadas")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("ComexApi.Models.Escala", b =>
                {
                    b.Navigation("ManifestosVinculados");
                });

            modelBuilder.Entity("ComexApi.Models.Manifesto", b =>
                {
                    b.Navigation("EscalasVinculadas");
                });
#pragma warning restore 612, 618
        }
    }
}
